@host = localhost:4143

### List available API calls
GET http://{{host}}/

### Random math fact
GET http://{{host}}/api/numbers

### Details of latest rocket launch
GET http://{{host}}/api/latest-launch

### List of rockets
GET http://{{host}}/api/rockets

### Details of specific rocket
GET http://{{host}}/api/rocket?id=5e9d0d96eda699382d09d1ee
