### List available API calls
GET http://localhost:8080/

### Random math fact
GET http://localhost:8080/api/numbers
host: localhost:8080

### Details of latest rocket launch
GET http://localhost:8080/api/latest-launch
host: localhost:8080

### List of rockets
GET http://localhost:8080/api/rockets
host: localhost:8080

### Details of specific rocket
GET http://localhost:8080/api/rocket?id=5e9d0d96eda699382d09d1ee
host: localhost:8080


