// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: lib/grpc/space.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for getting the latest launch
type LatestLaunchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestLaunchRequest) Reset() {
	*x = LatestLaunchRequest{}
	mi := &file_lib_grpc_space_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestLaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestLaunchRequest) ProtoMessage() {}

func (x *LatestLaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_grpc_space_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestLaunchRequest.ProtoReflect.Descriptor instead.
func (*LatestLaunchRequest) Descriptor() ([]byte, []int) {
	return file_lib_grpc_space_proto_rawDescGZIP(), []int{0}
}

// Request message for getting a specific rocket
type GetRocketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRocketRequest) Reset() {
	*x = GetRocketRequest{}
	mi := &file_lib_grpc_space_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRocketRequest) ProtoMessage() {}

func (x *GetRocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_grpc_space_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRocketRequest.ProtoReflect.Descriptor instead.
func (*GetRocketRequest) Descriptor() ([]byte, []int) {
	return file_lib_grpc_space_proto_rawDescGZIP(), []int{1}
}

func (x *GetRocketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request message for getting all rockets
type GetRocketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRocketsRequest) Reset() {
	*x = GetRocketsRequest{}
	mi := &file_lib_grpc_space_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRocketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRocketsRequest) ProtoMessage() {}

func (x *GetRocketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_grpc_space_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRocketsRequest.ProtoReflect.Descriptor instead.
func (*GetRocketsRequest) Descriptor() ([]byte, []int) {
	return file_lib_grpc_space_proto_rawDescGZIP(), []int{2}
}

// Response message for getting all rockets
type GetRocketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rockets       []*RocketSummary       `protobuf:"bytes,1,rep,name=rockets,proto3" json:"rockets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRocketsResponse) Reset() {
	*x = GetRocketsResponse{}
	mi := &file_lib_grpc_space_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRocketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRocketsResponse) ProtoMessage() {}

func (x *GetRocketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_grpc_space_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRocketsResponse.ProtoReflect.Descriptor instead.
func (*GetRocketsResponse) Descriptor() ([]byte, []int) {
	return file_lib_grpc_space_proto_rawDescGZIP(), []int{3}
}

func (x *GetRocketsResponse) GetRockets() []*RocketSummary {
	if x != nil {
		return x.Rockets
	}
	return nil
}

// Request message for getting a math fact
type GetMathFactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMathFactRequest) Reset() {
	*x = GetMathFactRequest{}
	mi := &file_lib_grpc_space_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMathFactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMathFactRequest) ProtoMessage() {}

func (x *GetMathFactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_grpc_space_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMathFactRequest.ProtoReflect.Descriptor instead.
func (*GetMathFactRequest) Descriptor() ([]byte, []int) {
	return file_lib_grpc_space_proto_rawDescGZIP(), []int{4}
}

// Response message containing launch details
type Launch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightNumber  int32                  `protobuf:"varint,1,opt,name=flight_number,json=flightNumber,proto3" json:"flight_number,omitempty"`
	MissionName   string                 `protobuf:"bytes,2,opt,name=mission_name,json=missionName,proto3" json:"mission_name,omitempty"`
	DateUtc       string                 `protobuf:"bytes,3,opt,name=date_utc,json=dateUtc,proto3" json:"date_utc,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Details       string                 `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Launch) Reset() {
	*x = Launch{}
	mi := &file_lib_grpc_space_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Launch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Launch) ProtoMessage() {}

func (x *Launch) ProtoReflect() protoreflect.Message {
	mi := &file_lib_grpc_space_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Launch.ProtoReflect.Descriptor instead.
func (*Launch) Descriptor() ([]byte, []int) {
	return file_lib_grpc_space_proto_rawDescGZIP(), []int{5}
}

func (x *Launch) GetFlightNumber() int32 {
	if x != nil {
		return x.FlightNumber
	}
	return 0
}

func (x *Launch) GetMissionName() string {
	if x != nil {
		return x.MissionName
	}
	return ""
}

func (x *Launch) GetDateUtc() string {
	if x != nil {
		return x.DateUtc
	}
	return ""
}

func (x *Launch) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Launch) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// Response message containing rocket details
type Rocket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	HeightMeters  float64                `protobuf:"fixed64,4,opt,name=height_meters,json=heightMeters,proto3" json:"height_meters,omitempty"`
	MassKg        int32                  `protobuf:"varint,5,opt,name=mass_kg,json=massKg,proto3" json:"mass_kg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rocket) Reset() {
	*x = Rocket{}
	mi := &file_lib_grpc_space_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rocket) ProtoMessage() {}

func (x *Rocket) ProtoReflect() protoreflect.Message {
	mi := &file_lib_grpc_space_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rocket.ProtoReflect.Descriptor instead.
func (*Rocket) Descriptor() ([]byte, []int) {
	return file_lib_grpc_space_proto_rawDescGZIP(), []int{6}
}

func (x *Rocket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rocket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rocket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rocket) GetHeightMeters() float64 {
	if x != nil {
		return x.HeightMeters
	}
	return 0
}

func (x *Rocket) GetMassKg() int32 {
	if x != nil {
		return x.MassKg
	}
	return 0
}

// Simplified rocket information
type RocketSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RocketSummary) Reset() {
	*x = RocketSummary{}
	mi := &file_lib_grpc_space_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RocketSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RocketSummary) ProtoMessage() {}

func (x *RocketSummary) ProtoReflect() protoreflect.Message {
	mi := &file_lib_grpc_space_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RocketSummary.ProtoReflect.Descriptor instead.
func (*RocketSummary) Descriptor() ([]byte, []int) {
	return file_lib_grpc_space_proto_rawDescGZIP(), []int{7}
}

func (x *RocketSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RocketSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response message containing math fact
type MathFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MathFact) Reset() {
	*x = MathFact{}
	mi := &file_lib_grpc_space_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MathFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathFact) ProtoMessage() {}

func (x *MathFact) ProtoReflect() protoreflect.Message {
	mi := &file_lib_grpc_space_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathFact.ProtoReflect.Descriptor instead.
func (*MathFact) Descriptor() ([]byte, []int) {
	return file_lib_grpc_space_proto_rawDescGZIP(), []int{8}
}

func (x *MathFact) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MathFact) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *MathFact) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *MathFact) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_lib_grpc_space_proto protoreflect.FileDescriptor

const file_lib_grpc_space_proto_rawDesc = "" +
	"\n" +
	"\x14lib/grpc/space.proto\x12\x05space\"\x15\n" +
	"\x13LatestLaunchRequest\"\"\n" +
	"\x10GetRocketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11GetRocketsRequest\"D\n" +
	"\x12GetRocketsResponse\x12.\n" +
	"\arockets\x18\x01 \x03(\v2\x14.space.RocketSummaryR\arockets\"\x14\n" +
	"\x12GetMathFactRequest\"\x9f\x01\n" +
	"\x06Launch\x12#\n" +
	"\rflight_number\x18\x01 \x01(\x05R\fflightNumber\x12!\n" +
	"\fmission_name\x18\x02 \x01(\tR\vmissionName\x12\x19\n" +
	"\bdate_utc\x18\x03 \x01(\tR\adateUtc\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x18\n" +
	"\adetails\x18\x05 \x01(\tR\adetails\"\x8c\x01\n" +
	"\x06Rocket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rheight_meters\x18\x04 \x01(\x01R\fheightMeters\x12\x17\n" +
	"\amass_kg\x18\x05 \x01(\x05R\x06massKg\"3\n" +
	"\rRocketSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"`\n" +
	"\bMathFact\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type2\x88\x02\n" +
	"\rLaunchService\x12>\n" +
	"\x0fGetLatestLaunch\x12\x1a.space.LatestLaunchRequest\x1a\r.space.Launch\"\x00\x125\n" +
	"\tGetRocket\x12\x17.space.GetRocketRequest\x1a\r.space.Rocket\"\x00\x12C\n" +
	"\n" +
	"GetRockets\x12\x18.space.GetRocketsRequest\x1a\x19.space.GetRocketsResponse\"\x00\x12;\n" +
	"\vGetMathFact\x12\x19.space.GetMathFactRequest\x1a\x0f.space.MathFact\"\x00B\x18Z\x16outerspace-go/lib/grpcb\x06proto3"

var (
	file_lib_grpc_space_proto_rawDescOnce sync.Once
	file_lib_grpc_space_proto_rawDescData []byte
)

func file_lib_grpc_space_proto_rawDescGZIP() []byte {
	file_lib_grpc_space_proto_rawDescOnce.Do(func() {
		file_lib_grpc_space_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_grpc_space_proto_rawDesc), len(file_lib_grpc_space_proto_rawDesc)))
	})
	return file_lib_grpc_space_proto_rawDescData
}

var file_lib_grpc_space_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_lib_grpc_space_proto_goTypes = []any{
	(*LatestLaunchRequest)(nil), // 0: space.LatestLaunchRequest
	(*GetRocketRequest)(nil),    // 1: space.GetRocketRequest
	(*GetRocketsRequest)(nil),   // 2: space.GetRocketsRequest
	(*GetRocketsResponse)(nil),  // 3: space.GetRocketsResponse
	(*GetMathFactRequest)(nil),  // 4: space.GetMathFactRequest
	(*Launch)(nil),              // 5: space.Launch
	(*Rocket)(nil),              // 6: space.Rocket
	(*RocketSummary)(nil),       // 7: space.RocketSummary
	(*MathFact)(nil),            // 8: space.MathFact
}
var file_lib_grpc_space_proto_depIdxs = []int32{
	7, // 0: space.GetRocketsResponse.rockets:type_name -> space.RocketSummary
	0, // 1: space.LaunchService.GetLatestLaunch:input_type -> space.LatestLaunchRequest
	1, // 2: space.LaunchService.GetRocket:input_type -> space.GetRocketRequest
	2, // 3: space.LaunchService.GetRockets:input_type -> space.GetRocketsRequest
	4, // 4: space.LaunchService.GetMathFact:input_type -> space.GetMathFactRequest
	5, // 5: space.LaunchService.GetLatestLaunch:output_type -> space.Launch
	6, // 6: space.LaunchService.GetRocket:output_type -> space.Rocket
	3, // 7: space.LaunchService.GetRockets:output_type -> space.GetRocketsResponse
	8, // 8: space.LaunchService.GetMathFact:output_type -> space.MathFact
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lib_grpc_space_proto_init() }
func file_lib_grpc_space_proto_init() {
	if File_lib_grpc_space_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_grpc_space_proto_rawDesc), len(file_lib_grpc_space_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_grpc_space_proto_goTypes,
		DependencyIndexes: file_lib_grpc_space_proto_depIdxs,
		MessageInfos:      file_lib_grpc_space_proto_msgTypes,
	}.Build()
	File_lib_grpc_space_proto = out.File
	file_lib_grpc_space_proto_goTypes = nil
	file_lib_grpc_space_proto_depIdxs = nil
}
